### ISSUE TITLE
Integration Tests

### ISSUE THREAD

**Issue by Bandisa** [COS301-SE-2023/Pronto#103]
# Todo
Write and document integration tests for:
- [x] auth
- [ ] prontoAuthPostConfirmation
- [x] prontoAuthPreConfirmation
- [x] Lecture View
- [ ] Institution View

**Comment by Bandisa** [comment]
# Update
- manual integration tests have been performed and demonstrated in meeting for `prontoAuthPostConfirmation `
# Next task
- documenting and automating integration tests for cloud functions

**Comment by Bandisa** [comment]
# Update
`amplify mock function prontoAuthPostConfirmation --event src/events/admin.event.json` runs and executes the event request but it immediately terminates after.
# Problem
Failing to run the function locally and have it listening for an event on a specific port as explained on https://github.com/aws-amplify/amplify-category-api/issues/384

**Comment by Bandisa** [comment]
I will write all unit tests using cypress and the live app, emulating resources like cloud functions in a repeatable manaer has proved to be a challenge, given the timeframe.

**Comment by Bandisa** [comment]
# Update
Dev will begin today.

**Comment by Bandisa** [comment]
# Update
- remainder of the tests will be written by @u21598267, as part of the CI/CD and Tester main role.
- I will implent auth and cloud funtion integration tests for the mobile view.

**Comment by u21598267** [comment]
## Update
- Workflow has been correctly adjusted to run the necessary cypress tests
- The tests that were present have been removed (will be explained below)
- SignIn testing has been redone and added to the repo and passed successfully

## Things to note
- The tests have been removed as I need to go one by one to find the failing tests and correct the tests or code
- Only the Web Application has the integration testing

**Comment by u21598267** [comment]
# Update
- The tests that were removed have been corrected
- The tests removed have been added
- New tests for the lecturer view have been added and there are only two pages left to test
## Problems 
- Hiding credentials for the GitHub actions has proven to be difficult
- We need to hide credentials otherwise it could be abused by someone to gain unauthorised access
- Research is currently being done to find a solution to this problem

**Comment by u21598267** [comment]
# Update 
- Lecture View integration tests completed
- The tests are likely to frequently fail as we are all working on this branch and making adjustments, the tests will be corrected as they fail
