### ISSUE TITLE
Class Diagram

### ISSUE THREAD

**Issue by ShashinGounden** [COS301-SE-2023/Pronto#20]
Please complete the class diagram for the system. We will be working on this as a team on Tuesday and it should be finalised and completed then. 

- [x] Complete the class diagram
- [x] Add it to documentation

**Comment by Tymac15** [comment]
class diagram is complete and under review before getting added to the documentation.

**Comment by Bandisa** [comment]
I have reviewed, suggested some changes, and approved of the class diagrams.

**Comment by Tymac15** [comment]
Final class diagram has been added to documentation, this issue is complete.
