### ISSUE TITLE
Unit test automation

### ISSUE THREAD

**Issue by ShashinGounden** [COS301-SE-2023/Pronto#24]
Please automate the unit tests that have been implemented. @Bandisa and @u21598267 should work together on this.

**Comment by Bandisa** [comment]
For backend we will be using Jest too, so I will probably extend the scripts that @u21598267 is setting up for frontend and add integration and e2e scripts by the end of the week.

**Comment by ShashinGounden** [comment]
Completed and using GitHub actions.
