### ISSUE TITLE
Code Quality Badges

### ISSUE THREAD

**Issue by ShashinGounden** [COS301-SE-2023/Pronto#26]
Please add code quality badges to the GitHub repo.

- [x] Code Coverage — Codecov

- [x] Build — AmplifyPush

- [x] Requirements — requires.io

- [x] Issue tracking — GitHub Issues

- [x] Monitoring — Uptime Robot

**Comment by u21598267** [comment]
Requirements badges do not work. Have tried multiple. Code coverage will not work unless we have testing in place that we can link. Will add at a time we have testing.

**Comment by ShashinGounden** [comment]
Completed and added to README

**Comment by Tymac15** [comment]
Jonel has managed to get the build badge working.
