### ISSUE TITLE
Pricing and Computing Matrics

### ISSUE THREAD

**Issue by Bandisa** [COS301-SE-2023/Pronto#301]
# Task
- Calculate Cost of compute units, runtime, and requests according to expected peak traffic of 10 SA institutions
- Calculate Pricing of the entire architecture
- Consult AWS support/cloud engineer for validation
# Status
- [x] Research
- [ ] Calculations
- [ ] Third party validation
- [ ] Documentation

**Comment by Bandisa** [comment]
# Update
- Research was completed today, 
- Studied some examples and equations as outlined in the aws documentation for each service used
- Base traffic considerations will be that off top 10 institutions in RSA and the traffic that that might be experienced at peak hours

**Comment by u21598267** [comment]
### Campus Navigation
Important information thus far: 
- We are using the Maps JavaScript API the price per request is $0.007 and increases from there.
- 50,000 simultaneous requests will be $350.
- We need to consider that we require pricing for another 3 APIs and the $350 mentioned is only for one API.

- [ ]  Research will be conducted on the point as mentioned earlier.

##Note:
A free tier is available for new accounts. This will include:
- Free requests (research to find out how many).
- $300 credit for the first 6 months.

**Comment by Bandisa** [comment]
Once notification is up, a meeting will be set up.

**Comment by Bandisa** [comment]
Seeing that we were denied a production account, and that this entire subsystem is on route to become a full in-house component as it stands, best to live its cost as a last minute calculation and calculate the rest.
