### ISSUE TITLE
Queries and mutations

### ISSUE THREAD

**Issue by ShashinGounden** [COS301-SE-2023/Pronto#33]
Please write queries and mutations in GraphQL:

- [x] Queries (Only for SPRINT 1)
- [x] Mutations (Only for SPRINT 1)
- [x] Subscriptions (Only for SPRINT 1)
- [x] Unit Tests for all of the above (Only for SPRINT 1)

**Comment by Bandisa** [comment]
# Update
I finally managed to setup the local dev environment after experiencing a few issues for the past 24 hours 🥲.
Off to write and test the queries and mutations.

**Comment by ShashinGounden** [comment]
Completed
