### ISSUE TITLE
Documentation and system design

### ISSUE THREAD

**Issue by ShashinGounden** [COS301-SE-2023/Pronto#5]
Please finalize the following and add it to the documentation:

- [x] Introduction
- [x] User stories
- [x] User characteristics
- [x] Functional Requirements
- [x] Use case diagram
- [x] Class Diagram
- [x] Service Contracts
- [x] Quality Requirements
- [x] Architectural requirements
- [x] Tech requirements

**Comment by ShashinGounden** [comment]
@Bandisa Please add the quality requirements into the Google Doc.

**Comment by Bandisa** [comment]
I have added the quality requirements, please verify and proof read.

**Comment by Bandisa** [comment]
# Update
I added the high level architecture, with an overview of the architecture pattern used and microservices used.
# Missing
Need to add the service contracts.

**Comment by ShashinGounden** [comment]
Assigned @u20612894 to do tech requirements.

**Comment by ShashinGounden** [comment]
Completed.
