### ISSUE TITLE
User Pool Error

### ISSUE THREAD

**Issue by ShashinGounden** [COS301-SE-2023/Pronto#72]
Receive the following error after verifying an email with the code sent to it:
![Screenshot 2023-06-02 at 17 45 03](https://github.com/COS301-SE-2023/Pronto/assets/101881243/47f1f452-d187-44b4-9baf-93a1008fd6cc)

Note that the following was done before the error:

-Created Account
 
Uses this code to create an account (works fine):
` await Auth.signUp({
        username: email,
        password,
        attributes: { address, email, family_name: surname, name },
      });`

- Verify Verification Code (works fine and verifies user, but then throws this error)
` try {
      response = await Auth.confirmSignUp(email, code);

      //need to add user to a user group here?

      navigation.navigate("Login");
    } catch (e) {
      Alert.alert("Error", e.message);
    }`

This might be a possible solution but will need you to confirm:
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#adminAddUserToGroup-property

**Comment by Bandisa** [comment]
Addressed by #60
